### ISSUE TITLE
Live registration UX improvements

### ISSUE THREAD

**Issue by exploide** [osmandapp/osmandapp.github.io#126]
I spotted two things that could be improved during the registration process.

The OsmAnd Live registration form does not seem to accept all types of BTC addresses. Probably related to SegWit?! Instead of showing a message like "Please validate bitcoin address", it would be nice to either accept also other types of addresses or explain in the message that this format is not supported.

Additionally, when unregistering (following the advice "to delete account - enter empty BTC address") the confirmation message "You successfully registered as a recipient." is shown. Would be better to show something like "You successfully unregistered as a recipient." or "You successfully deleted your OsmAnd Live account."

**Comment by vshcherb** [comment]
Thanks for feedback!
