### ISSUE TITLE
The Blog's RSS feed is invalid

### ISSUE THREAD

**Issue by somini** [osmandapp/osmandapp.github.io#127]
https://validator.w3.org/feed/check.cgi?url=https://osmand.net/rss.xml

Main Issues:
- All posts must have a unique ID. It can be the post URL.
- Missing `self` link: https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html
- The HTML in the description must be escaped with `CDATA`. https://cyber.harvard.edu/rss/encodingDescriptions.html#example2EncodingHtmlWithinACdataSection
- Some dates are incorrectly formatted.

The feed URL should also be added to the blog HTML. Here:
https://github.com/osmandapp/osmandapp.github.io/blob/0319de879a44f98463c982d359d8fe88a6dc180c/website/blog.php#L8-L23
Add:
```
<link rel="alternate" type="application/rss+xml" title="OsmAnd Blog" href="/rss.xml">
```

---

I could open a PR for this changes, but how do new blog posts are created?

**Comment by vshcherb** [comment]
As for now they are actually created manually. Main our target is https://blogs.openstreetmap.org/

Please create PR.
