### ISSUE TITLE
Inclusion in Planet F-Droid

### ISSUE THREAD

**Issue by vanitasvitae** [osmandapp/osmandapp.github.io#137]
Hi!
I'm currently in the process of setting up [Planet F-Droid](https://fdroid.gitlab.io/planet/), which will be a feed aggregator focussed on free software, especially android development. See [the wiki](https://gitlab.com/fdroid/planet/wikis/Planet-F-Droid) for more information.

Right now I'm populating the site with feeds.
I'd like to ask, whether it is okay for you, if I'd include the OsmAnd blog in the planet. The site is updated every hour to fetch new blog articles, which are then combined into a single feed.

Greetings,
Paul

**Comment by vshcherb** [comment]
Sure we will be very happy!

**Comment by vanitasvitae** [comment]
I added the blog :)
