### ISSUE TITLE
Error translating into Brazilian Portuguese

### ISSUE THREAD

**Issue by eduaddad** [osmandapp/osmandapp.github.io#150]
I tried to send the files that translate to Portuguese but it did not work.

![Captura de Tela (48)](https://user-images.githubusercontent.com/16819380/60682499-e7400d00-9e69-11e9-88e8-0892695400e6.png)

**Comment by vshcherb** [comment]
You need to create a fork and push to fork. So here you need to create a fork.https://github.com/osmandapp/osmandapp.github.io

After that you can create pull request

**Comment by eduaddad** [comment]
https://github.com/eduaddad/osmandapp.github.io

**Comment by eduaddad** [comment]
@vshcherb  The link to the fork.
