### ISSUE TITLE
Live registration fails

### ISSUE THREAD

**Issue by pludi** [osmandapp/osmandapp.github.io#155]
Trying to sign up it fails with a 401 error, apparently proxied from the OSM servers as the osmand.net server responds with a `200 OK`.

Credentials are correct as verified by logging in to OSM in a private window.

Only issues that I could see regarding my account are:

1. I changed my nick, since it originally contained a space character, and I assumed that might be an issue
2. My password is overly long at 128 characters, including special chars

**Comment by pludi** [comment]
Definitely an issue with the password length. I temporarily changed it to something shorter, and registration worked.

**Comment by vshcherb** [comment]
This is even better cause we recommend to use temporary password to avoid any private information to be shared with us

**Comment by pludi** [comment]
Maybe add a note about a maximum password length then?
