### ISSUE TITLE
help/technical-articles broken link or missing content

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/osmandapp.github.io#162]
This section of your technical articles page appears to be missing. Clicking the link [Map Generation Process](https://osmand.net/help-online/technical-articles#Map_Generation_Process) doesn't bring the user anywhere.

https://github.com/osmandapp/osmandapp.github.io/blob/ef365926c5131a3305e509b7bb6662ed451a8ba5/website/help/technical-articles.html#L15

**Comment by goldfndr** [comment]
relevant commit: https://github.com/osmandapp/osmandapp.github.io/commit/e3aa114120834f6a4e49861edbc42f983250ddcf#diff-360401e44c994567ef22b307d8df2739
