### ISSUE TITLE
Website mistake

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/osmandapp.github.io#172]
I think there's a mistake on the http://osmand.net/build_it page.

In the paragraph that describes "penalty_transition" is this:  For example, motorway - 10, trunk - 15, if user goes _from **trunk to motorway** penalty will be_ 5 seconds (=15 - 10). This penalty will be used by A* algorithm. There is _no penalty if user goes from **trunk to motorway**_ and there is no penalty if route continues from motorway to motorway.

I'm pretty sure that the first "trunk to motorway" should actually be "motorway to trunk," should it not?

**Comment by jfburke3** [comment]
@vshcherb @EugeneZmeuk 

Well, now another problem is there, in the other direction.  The second "trunk to motorway" reference was *also* changed, which I think is wrong.  Please correct me if I've misunderstood how the routing algorithm works.

"There is _no penalty if user goes from **motorway to trunk**_ and there is no penalty if route continues from motorway to motorway." 

Is that correct?

**Comment by vshcherb** [comment]
I'm not sure, we have bidirectional search so penalty is always applied I guess when the road class is changed. In 1-directional search obvioulsy it will be only for primary -> motorway but not other way around.
