### ISSUE TITLE
What is osmand.de?

### ISSUE THREAD

**Issue by rugk** [osmandapp/osmandapp.github.io#180]
What is this https://www.osmand.de/ website? Is it an outdated website? Some rip-off? Spam?

When [searching](https://duckduckgo.com/?t=ffab&q=osmand&ia=web) for Osmand it is unfortunately the first result, and it is clerarly about the app:
![grafik](https://user-images.githubusercontent.com/11966684/105033999-2ab49900-5a59-11eb-8be8-4559569d2765.png)

**Comment by vshcherb** [comment]
It's actually not bad :-) It's just outdated but we don't control it. 
It was done in early OsmAnd ages probably somebody was practicing HTML
