### ISSUE TITLE
How to prepare raster maps - Alternative method

### ISSUE THREAD

**Issue by bellera** [osmandapp/osmandapp.github.io#182]
I think https://osmand.net/features/online-maps-plugin#Prepare_raster_maps should updated. Although the **Maps Creator Tool** is interesting for doing the work with a computer,` .sqlitedb` maps can be (now) generated with OsmAnd.
Just edit the **online source** selecting `SQLiteDB file` at **Storage format**. After that, use the **Download** method explained at https://osmand.net/features/online-maps-plugin#How_to_use_A The download will update your `.sqlitedb` map. After that, If you want, you can make a backup of the `.sqlitedb` to your computer. The main difference are that you will not have the tiles in metainfo format (on file for each tile). **Maps Creator Tool**  downloads the tiles in metainfo format and after that you tells him to create the `.sqlitedb` file.

**Comment by vshcherb** [comment]
We're in the middle of documentation migration process and it is going to be fully updated - https://docs.osmand.net/en/main@latest/osmand/map/online-raster-maps#prepare--copy-raster-maps-to-device
