### ISSUE TITLE
OpenStreetMap typo (again)

### ISSUE THREAD

**Issue by rbovard** [osmandapp/osmandapp.github.io#26]
With PR #15, I fixed some typo `Open Street Map` > `OpenStreetMap` and now the typo is here again:
* https://github.com/osmandapp/osmandapp.github.io/blob/master/website/blocks/footer.html#L31
* https://github.com/osmandapp/osmandapp.github.io/pull/15/files#diff-ca01ee22b3b4def8e3076c060ce15843L39

Any idea why? I cannot found the guilty commit in history https://github.com/osmandapp/osmandapp.github.io/commits/master/website/blocks/footer.html

**Comment by rbovard** [comment]
Mmmh ok but there some other typos that I fixed in my PR but are present again:
- https://github.com/osmandapp/osmandapp.github.io/blob/master/website/feature_articles/main.html#L138
- https://github.com/osmandapp/osmandapp.github.io/blob/master/website/feature_articles/main.html#L87
- https://github.com/osmandapp/osmandapp.github.io/blob/master/website/feature_articles/main.html#L112
- https://github.com/osmandapp/osmandapp.github.io/blob/master/website/feature_articles/main.html#L138

**Comment by vshcherb** [comment]
Hmm is it possibly a merge issue?

**Comment by rbovard** [comment]
I realy don't understand_ some fixes are ok, some not...

**Comment by vshcherb** [comment]
Could you please create another pull request and I will have a close look it, we are not going to do any other changes soon.

**Comment by rbovard** [comment]
@vshcherb Done!
