### ISSUE TITLE
Add a report "ranking_by_user_by_month.php"

### ISSUE THREAD

**Issue by Binnette** [osmandapp/osmandapp.github.io#44]
Hi, can you please add a report that simply display ranking for 1 only user ?

Parameters will be :
1. user='the_user_name' (mandatory)
2. date='YYYY-MM (default value = current date)
3. region='the_region_name' (default value = worldwide)

I don't care about adding a page in the website for this report. I just want to call this report from an Android application or something else.

Thanks a lot !

**Comment by Binnette** [comment]
I have a PR #45 
But I can not test it because I do not have the database.
Please consider take a look at it.

**Comment by vshcherb** [comment]
Merged
