### ISSUE TITLE
Lack of domain unification causes CORS errors on OSM Live page

### ISSUE THREAD

**Issue by M1dgard** [osmandapp/osmandapp.github.io#50]
osmand.net and www.osmand.net exist as duplicate sites, neither redirects to the other. This causes

![Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.osmand.net/api/osmlive_status. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).](https://user-images.githubusercontent.com/4283376/30220485-da7b2c5e-94bf-11e7-8cdd-b97d2fac51e8.png)

on https://osmand.net/osm_live and a failure to load the data. Suggested easy fix: change the server configuration to redirect (probably with `301 Moved Permanently`) all requests for [osmand.net](https://osmand.net) to [www.osmand.net](https://www.osmand.net).

**Comment by vshcherb** [comment]
It supposed to be only osmand.net (www. actually should be redirecting). 

Now I've found that new code was added but it should be done differently i.e. it should be just done on the server side
