### ISSUE TITLE
Website: update dead link in help.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/osmandapp.github.io#7]
The link to [google groups](http://groups.google.com/forum/?fromgroups#!forum/osmand?) is dead on the [help page](http://osmand.net/help-online), but [this one](https://groups.google.com/forum/#!forum/osmand) seems to be the right one.

Also noticed the [talk page](http://wiki.openstreetmap.org/wiki/Talk:OsmAnd) on openstreetmaps has some useful information, and seems like openstreetmaps.org is an increasingly useful resource for OsmAnd info but there is no link on the help page.

**Comment by vshcherb** [comment]
Fixed
